// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Account defender risk assessment.
public struct AccountDefenderAssessment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Labels for this request.
  public var labels: [AccountDefenderAssessment.AccountDefenderLabel] = []

  /// Initialize a new instance of `AccountDefenderAssessment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccountDefenderAssessment().with { $0.labels = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Labels returned by account defender for this request.
  /// Ensure that applications can handle values not explicitly listed.
  public enum AccountDefenderLabel: Codable, Equatable, Sendable {
    /// Default unspecified type.
    case unspecified
    /// The request matches a known good profile for the user.
    case profileMatch
    /// The request is potentially a suspicious login event and must be further
    /// verified either through multi-factor authentication or another system.
    case suspiciousLoginActivity
    /// The request matched a profile that previously had suspicious account
    /// creation behavior. This can mean that this is a fake account.
    case suspiciousAccountCreation
    /// The account in the request has a high number of related accounts. It does
    /// not necessarily imply that the account is bad but can require further
    /// investigation.
    case relatedAccountsNumberHigh
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .profileMatch: return 1
      case .suspiciousLoginActivity: return 2
      case .suspiciousAccountCreation: return 3
      case .relatedAccountsNumberHigh: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACCOUNT_DEFENDER_LABEL_UNSPECIFIED"
      case .profileMatch: return "PROFILE_MATCH"
      case .suspiciousLoginActivity: return "SUSPICIOUS_LOGIN_ACTIVITY"
      case .suspiciousAccountCreation: return "SUSPICIOUS_ACCOUNT_CREATION"
      case .relatedAccountsNumberHigh: return "RELATED_ACCOUNTS_NUMBER_HIGH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AccountDefenderLabel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACCOUNT_DEFENDER_LABEL_UNSPECIFIED": self = .unspecified
      case "PROFILE_MATCH": self = .profileMatch
      case "SUSPICIOUS_LOGIN_ACTIVITY": self = .suspiciousLoginActivity
      case "SUSPICIOUS_ACCOUNT_CREATION": self = .suspiciousAccountCreation
      case "RELATED_ACCOUNTS_NUMBER_HIGH": self = .relatedAccountsNumberHigh
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AccountDefenderLabel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .profileMatch
      case 2: self = .suspiciousLoginActivity
      case 3: self = .suspiciousAccountCreation
      case 4: self = .relatedAccountsNumberHigh
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .profileMatch: return try container.encode(1)
      case .suspiciousLoginActivity: return try container.encode(2)
      case .suspiciousAccountCreation: return try container.encode(3)
      case .relatedAccountsNumberHigh: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.AccountDefenderAssessment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
