// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Settings specific to keys that can be used by Android apps.
public struct AndroidKeySettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. If set to true, allowed_package_names are not enforced.
  public var allowAllPackageNames: Swift.Bool = Swift.Bool()

  /// Optional. Android package names of apps allowed to use the key.
  /// Example: 'com.companyname.appname'
  /// Each key supports a maximum of 250 package names. To use a key on more
  /// apps, set `allow_all_package_names` to true. When this is set, you
  /// are responsible for validating the package name by checking the
  /// `token_properties.android_package_name` field in each assessment response
  /// against your list of allowed package names.
  public var allowedPackageNames: [Swift.String] = []

  /// Optional. Set to true for keys that are used in an Android application that
  /// is available for download in app stores in addition to the Google Play
  /// Store.
  public var supportNonGoogleAppStoreDistribution: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AndroidKeySettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AndroidKeySettings().with { $0.allowAllPackageNames = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let allowAllPackageNames = CodingKeys(stringValue: "allowAllPackageNames")
    static let allowedPackageNames = CodingKeys(stringValue: "allowedPackageNames")
    static let supportNonGoogleAppStoreDistribution = CodingKeys(
      stringValue: "supportNonGoogleAppStoreDistribution")

    static let _knownKeys: Set<Swift.String> = [
      "allowAllPackageNames",
      "allowedPackageNames",
      "supportNonGoogleAppStoreDistribution",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowAllPackageNames) {
      self.allowAllPackageNames = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .allowedPackageNames)
    {
      self.allowedPackageNames = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .supportNonGoogleAppStoreDistribution)
    {
      self.supportNonGoogleAppStoreDistribution = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.allowAllPackageNames, forKey: .allowAllPackageNames)
    try container.encode(self.allowedPackageNames, forKey: .allowedPackageNames)
    try container.encode(
      self.supportNonGoogleAppStoreDistribution, forKey: .supportNonGoogleAppStoreDistribution)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.AndroidKeySettings"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
