// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Contains fields that are required to perform Apple-specific integrity checks.
public struct AppleDeveloperId: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Input only. A private key (downloaded as a text file with a .p8
  /// file extension) generated for your Apple Developer account. Ensure that
  /// Apple DeviceCheck is enabled for the private key.
  public var privateKey: Swift.String = Swift.String()

  /// Required. The Apple developer key ID (10-character string).
  public var keyId: Swift.String = Swift.String()

  /// Required. The Apple team ID (10-character string) owning the provisioning
  /// profile used to build your application.
  public var teamId: Swift.String = Swift.String()

  /// Initialize a new instance of `AppleDeveloperId`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppleDeveloperId().with { $0.privateKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.AppleDeveloperId"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
