// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A reCAPTCHA Enterprise assessment resource.
public struct Assessment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource name for the Assessment in the format
  /// `projects/{project}/assessments/{assessment}`.
  public var name: Swift.String = Swift.String()

  /// Optional. The event being assessed.
  public var event: Event? = nil

  /// Output only. The risk analysis result for the event being assessed.
  public var riskAnalysis: RiskAnalysis? = nil

  /// Output only. Properties of the provided event token.
  public var tokenProperties: TokenProperties? = nil

  /// Optional. Account verification information for identity verification. The
  /// assessment event must include a token and site key to use this feature.
  public var accountVerification: AccountVerificationInfo? = nil

  /// Output only. Assessment returned by Account defense when an account
  /// identifier is provided.
  public var accountDefenderAssessment: AccountDefenderAssessment? = nil

  /// Optional. The private password leak verification field contains the
  /// parameters that are used to to check for leaks privately without sharing
  /// user credentials.
  public var privatePasswordLeakVerification: PrivatePasswordLeakVerification? = nil

  /// Output only. Assessment returned when firewall policies belonging to the
  /// project are evaluated using the field firewall_policy_evaluation.
  public var firewallPolicyAssessment: FirewallPolicyAssessment? = nil

  /// Output only. Assessment returned by Fraud Prevention when TransactionData
  /// is provided.
  public var fraudPreventionAssessment: FraudPreventionAssessment? = nil

  /// Output only. Fraud Signals specific to the users involved in a payment
  /// transaction.
  public var fraudSignals: FraudSignals? = nil

  /// Output only. Assessment returned when a site key, a token, and a phone
  /// number as `user_id` are provided. SMS defense needs to be enabled.
  public var phoneFraudAssessment: PhoneFraudAssessment? = nil

  /// Optional. The environment creating the assessment. This describes your
  /// environment (the system invoking CreateAssessment), NOT the environment of
  /// your user.
  public var assessmentEnvironment: AssessmentEnvironment? = nil

  /// Output only. Provides information about the policy evaluation for this
  /// assessment.
  public var policyEvaluation: PolicyEvaluation? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Assessment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Assessment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let event = CodingKeys(stringValue: "event")
    static let riskAnalysis = CodingKeys(stringValue: "riskAnalysis")
    static let tokenProperties = CodingKeys(stringValue: "tokenProperties")
    static let accountVerification = CodingKeys(stringValue: "accountVerification")
    static let accountDefenderAssessment = CodingKeys(stringValue: "accountDefenderAssessment")
    static let privatePasswordLeakVerification = CodingKeys(
      stringValue: "privatePasswordLeakVerification")
    static let firewallPolicyAssessment = CodingKeys(stringValue: "firewallPolicyAssessment")
    static let fraudPreventionAssessment = CodingKeys(stringValue: "fraudPreventionAssessment")
    static let fraudSignals = CodingKeys(stringValue: "fraudSignals")
    static let phoneFraudAssessment = CodingKeys(stringValue: "phoneFraudAssessment")
    static let assessmentEnvironment = CodingKeys(stringValue: "assessmentEnvironment")
    static let policyEvaluation = CodingKeys(stringValue: "policyEvaluation")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "event",
      "riskAnalysis",
      "tokenProperties",
      "accountVerification",
      "accountDefenderAssessment",
      "privatePasswordLeakVerification",
      "firewallPolicyAssessment",
      "fraudPreventionAssessment",
      "fraudSignals",
      "phoneFraudAssessment",
      "assessmentEnvironment",
      "policyEvaluation",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.event = try container.decodeIfPresent(Event.self, forKey: .event)
    self.riskAnalysis = try container.decodeIfPresent(RiskAnalysis.self, forKey: .riskAnalysis)
    self.tokenProperties = try container.decodeIfPresent(
      TokenProperties.self, forKey: .tokenProperties)
    self.accountVerification = try container.decodeIfPresent(
      AccountVerificationInfo.self, forKey: .accountVerification)
    self.accountDefenderAssessment = try container.decodeIfPresent(
      AccountDefenderAssessment.self, forKey: .accountDefenderAssessment)
    self.privatePasswordLeakVerification = try container.decodeIfPresent(
      PrivatePasswordLeakVerification.self, forKey: .privatePasswordLeakVerification)
    self.firewallPolicyAssessment = try container.decodeIfPresent(
      FirewallPolicyAssessment.self, forKey: .firewallPolicyAssessment)
    self.fraudPreventionAssessment = try container.decodeIfPresent(
      FraudPreventionAssessment.self, forKey: .fraudPreventionAssessment)
    self.fraudSignals = try container.decodeIfPresent(FraudSignals.self, forKey: .fraudSignals)
    self.phoneFraudAssessment = try container.decodeIfPresent(
      PhoneFraudAssessment.self, forKey: .phoneFraudAssessment)
    self.assessmentEnvironment = try container.decodeIfPresent(
      AssessmentEnvironment.self, forKey: .assessmentEnvironment)
    self.policyEvaluation = try container.decodeIfPresent(
      PolicyEvaluation.self, forKey: .policyEvaluation)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.event, forKey: .event)
    try container.encodeIfPresent(self.riskAnalysis, forKey: .riskAnalysis)
    try container.encodeIfPresent(self.tokenProperties, forKey: .tokenProperties)
    try container.encodeIfPresent(self.accountVerification, forKey: .accountVerification)
    try container.encodeIfPresent(
      self.accountDefenderAssessment, forKey: .accountDefenderAssessment)
    try container.encodeIfPresent(
      self.privatePasswordLeakVerification, forKey: .privatePasswordLeakVerification)
    try container.encodeIfPresent(self.firewallPolicyAssessment, forKey: .firewallPolicyAssessment)
    try container.encodeIfPresent(
      self.fraudPreventionAssessment, forKey: .fraudPreventionAssessment)
    try container.encodeIfPresent(self.fraudSignals, forKey: .fraudSignals)
    try container.encodeIfPresent(self.phoneFraudAssessment, forKey: .phoneFraudAssessment)
    try container.encodeIfPresent(self.assessmentEnvironment, forKey: .assessmentEnvironment)
    try container.encodeIfPresent(self.policyEvaluation, forKey: .policyEvaluation)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.Assessment"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
