// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Bot information and metadata.
public struct Bot: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Enumerated string value that indicates the identity of the bot,
  /// formatted in kebab-case. Current example values include the following:
  ///
  /// * google-agent - AI_AGENT
  /// * browser-base - AI_AGENT
  /// * chat-gpt - AI_AGENT
  /// * aws-bedrock - AI_AGENT
  /// * cybaa-bot - AI_AGENT
  /// * cloudflare - AI_AGENT
  /// * payhawk - AI_AGENT
  /// * duck-duck-go - SEARCH_INDEXER
  /// * mediaboard - CONTENT_SCRAPER
  /// * marker-io - AI_AGENT
  /// * broadcom - AI_AGENT
  /// * anchor-browser - AI_AGENT
  /// * shopify - AI_AGENT
  /// * stackscope - CONTENT_SCRAPER
  /// * manus - AI_AGENT
  /// * kernel-sh - AI_AGENT
  /// * zvelo - SEARCH_INDEXER
  ///
  /// Ensure that your applications can handle identifier values not explicitly
  /// listed here. Deprecated values might take some time to stop showing
  /// up in responses. New values can be pushed so this list should be taken
  /// as non exhaustive.
  public var name: Swift.String = Swift.String()

  /// Optional. Enumerated field representing the type of bot.
  public var botType: Bot.BotType = Bot.BotType()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Bot`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Bot().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let botType = CodingKeys(stringValue: "botType")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "botType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Bot.BotType.self, forKey: .botType) {
      self.botType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.botType, forKey: .botType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Types of bots.
  /// Ensure that applications can handle values not explicitly listed.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum BotType: Codable, Equatable, Sendable {
    /// Default unspecified type.
    case unspecified
    /// Software program that interacts with a site and performs tasks
    /// autonomously.
    case aiAgent
    /// Software that extracts specific data from sites for use.
    case contentScraper
    /// Software that crawls sites and stores content for the purpose of
    /// efficient retrieval, likely as part of a search engine.
    case searchIndexer
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .aiAgent: return 1
      case .contentScraper: return 2
      case .searchIndexer: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BOT_TYPE_UNSPECIFIED"
      case .aiAgent: return "AI_AGENT"
      case .contentScraper: return "CONTENT_SCRAPER"
      case .searchIndexer: return "SEARCH_INDEXER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BotType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BOT_TYPE_UNSPECIFIED": self = .unspecified
      case "AI_AGENT": self = .aiAgent
      case "CONTENT_SCRAPER": self = .contentScraper
      case "SEARCH_INDEXER": self = .searchIndexer
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BotType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .aiAgent
      case 2: self = .contentScraper
      case 3: self = .searchIndexer
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("BOT_TYPE_UNSPECIFIED")
      case .aiAgent: return try container.encode("AI_AGENT")
      case .contentScraper: return try container.encode("CONTENT_SCRAPER")
      case .searchIndexer: return try container.encode("SEARCH_INDEXER")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.Bot"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
