// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A rule to configure the behavior of reCAPTCHA for conditionally presenting a
/// challenge.
public struct ChallengeRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. A CEL condition that must be met for this rule to apply.
  /// If unspecified, the rule applies unconditionally.
  /// The following fields can be referenced in the condition:
  /// * `score`
  /// * `user_ip_address`
  /// * `user_asn`
  /// * `user_agent`
  /// * `verified_bots.name`
  /// * `verified_bots.bot_type`
  ///
  /// Examples:
  /// * `score < 0.5`
  /// * `user_ip_address == "123.45.67.89"`
  /// * `user_agent.contains("Chrome")`
  /// * `score < 0.5 && user_ip_address == "123.45.67.89"`
  public var condition: Swift.String = Swift.String()

  /// Required. The outcome to apply when this challenge rule matches.
  public var outcome: OneOf_Outcome? = nil

  /// Initialize a new instance of `ChallengeRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ChallengeRule().with { $0.condition = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case condition = "condition"
    case noChallenge = "noChallenge"
    case challenge = "challenge"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.condition = try container.decode(Swift.String.self, forKey: .condition)

    var outcome: OneOf_Outcome? = nil
    let outcomeCheckAndSet = {
      if outcome != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'outcome'"))
      }
      outcome = $0
    }
    if let noChallenge = try container.decodeIfPresent(
      ChallengeRule.NoChallengeOutcome?.self, forKey: .noChallenge)
    {
      try outcomeCheckAndSet(.noChallenge(noChallenge))
    }
    if let challenge = try container.decodeIfPresent(
      ChallengeRule.ChallengeOutcome?.self, forKey: .challenge)
    {
      try outcomeCheckAndSet(.challenge(challenge))
    }
    self.outcome = outcome
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.condition, forKey: .condition)

    if let choice = self.outcome {
      switch choice {
      case .noChallenge(let value):
        try container.encode(value, forKey: .noChallenge)
      case .challenge(let value):
        try container.encode(value, forKey: .challenge)
      }
    }
  }

  /// An outcome that indicates that no challenge should be presented to the
  /// user.
  public struct NoChallengeOutcome: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `NoChallengeOutcome`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NoChallengeOutcome().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.recaptchaenterprise.v1.ChallengeRule.NoChallengeOutcome"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// An outcome that indicates that a challenge of a specified difficulty should
  /// be presented to the user.
  public struct ChallengeOutcome: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The difficulty of the challenge to present to the user.
    /// If unspecified, `BALANCE` is used.
    public var difficulty: WebKeySettings.ChallengeSecurityPreference =
      WebKeySettings.ChallengeSecurityPreference()

    /// Initialize a new instance of `ChallengeOutcome`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ChallengeOutcome().with { $0.difficulty = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.recaptchaenterprise.v1.ChallengeRule.ChallengeOutcome"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Required. The outcome to apply when this challenge rule matches.
  public enum OneOf_Outcome: Codable, Equatable, Sendable {
    /// Do not present a challenge to the user.
    indirect case noChallenge(ChallengeRule.NoChallengeOutcome?)
    /// Present a challenge to the user.
    indirect case challenge(ChallengeRule.ChallengeOutcome?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.ChallengeRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
