// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Metrics related to challenges.
public struct ChallengeMetrics: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Count of reCAPTCHA checkboxes or badges rendered. This is mostly equivalent
  /// to a count of pageloads for pages that include reCAPTCHA.
  public var pageloadCount: Swift.Int64 = Swift.Int64()

  /// Count of nocaptchas (successful verification without a challenge) issued.
  public var nocaptchaCount: Swift.Int64 = Swift.Int64()

  /// Count of submitted challenge solutions that were incorrect or otherwise
  /// deemed suspicious such that a subsequent challenge was triggered.
  public var failedCount: Swift.Int64 = Swift.Int64()

  /// Count of nocaptchas (successful verification without a challenge) plus
  /// submitted challenge solutions that were correct and resulted in
  /// verification.
  public var passedCount: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ChallengeMetrics`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ChallengeMetrics().with { $0.pageloadCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let pageloadCount = CodingKeys(stringValue: "pageloadCount")
    static let nocaptchaCount = CodingKeys(stringValue: "nocaptchaCount")
    static let failedCount = CodingKeys(stringValue: "failedCount")
    static let passedCount = CodingKeys(stringValue: "passedCount")

    static let _knownKeys: Set<Swift.String> = [
      "pageloadCount",
      "nocaptchaCount",
      "failedCount",
      "passedCount",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .pageloadCount) {
      self.pageloadCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .nocaptchaCount) {
      self.nocaptchaCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .failedCount) {
      self.failedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .passedCount) {
      self.passedCount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.pageloadCount, forKey: .pageloadCount)
    try container.encode(self.nocaptchaCount, forKey: .nocaptchaCount)
    try container.encode(self.failedCount, forKey: .failedCount)
    try container.encode(self.passedCount, forKey: .passedCount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.ChallengeMetrics"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
