// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Information about a verification endpoint that can be used for 2FA.
public struct EndpointVerificationInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Token to provide to the client to trigger endpoint
  /// verification. It must be used within 15 minutes.
  public var requestToken: Swift.String = Swift.String()

  /// Output only. Timestamp of the last successful verification for the
  /// endpoint, if any.
  public var lastVerificationTime: GoogleWKT.Timestamp? = nil

  public var endpoint: OneOf_Endpoint? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EndpointVerificationInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EndpointVerificationInfo().with { $0.emailAddress = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let emailAddress = CodingKeys(stringValue: "emailAddress")
    static let phoneNumber = CodingKeys(stringValue: "phoneNumber")
    static let requestToken = CodingKeys(stringValue: "requestToken")
    static let lastVerificationTime = CodingKeys(stringValue: "lastVerificationTime")

    static let _knownKeys: Set<Swift.String> = [
      "emailAddress",
      "phoneNumber",
      "requestToken",
      "lastVerificationTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestToken) {
      self.requestToken = value
    }
    self.lastVerificationTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .lastVerificationTime)

    var endpoint: OneOf_Endpoint? = nil
    let endpointCheckAndSet = {
      if endpoint != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'endpoint'"))
      }
      endpoint = $0
    }
    if let emailAddress = try container.decodeIfPresent(Swift.String.self, forKey: .emailAddress) {
      try endpointCheckAndSet(.emailAddress(emailAddress))
    }
    if let phoneNumber = try container.decodeIfPresent(Swift.String.self, forKey: .phoneNumber) {
      try endpointCheckAndSet(.phoneNumber(phoneNumber))
    }
    self.endpoint = endpoint
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.requestToken, forKey: .requestToken)
    try container.encodeIfPresent(self.lastVerificationTime, forKey: .lastVerificationTime)

    if let choice = self.endpoint {
      switch choice {
      case .emailAddress(let value):
        try container.encode(value, forKey: .emailAddress)
      case .phoneNumber(let value):
        try container.encode(value, forKey: .phoneNumber)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_Endpoint: Codable, Equatable, Sendable {
    /// Email address for which to trigger a verification request.
    case emailAddress(Swift.String)
    /// Phone number for which to trigger a verification request. Should be given
    /// in E.164 format.
    case phoneNumber(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.EndpointVerificationInfo"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
