// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An individual action. Each action represents what to do if a policy
/// matches.
public struct FirewallAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var firewallActionOneof: OneOf_FirewallActionOneof? = nil

  /// Initialize a new instance of `FirewallAction`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FirewallAction().with { $0.allow = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case allow = "allow"
    case block = "block"
    case includeRecaptchaScript = "includeRecaptchaScript"
    case redirect = "redirect"
    case substitute = "substitute"
    case setHeader = "setHeader"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var firewallActionOneof: OneOf_FirewallActionOneof? = nil
    let firewallActionOneofCheckAndSet = {
      if firewallActionOneof != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'firewallActionOneof'"))
      }
      firewallActionOneof = $0
    }
    if let allow = try container.decodeIfPresent(FirewallAction.AllowAction?.self, forKey: .allow) {
      try firewallActionOneofCheckAndSet(.allow(allow))
    }
    if let block = try container.decodeIfPresent(FirewallAction.BlockAction?.self, forKey: .block) {
      try firewallActionOneofCheckAndSet(.block(block))
    }
    if let includeRecaptchaScript = try container.decodeIfPresent(
      FirewallAction.IncludeRecaptchaScriptAction?.self, forKey: .includeRecaptchaScript)
    {
      try firewallActionOneofCheckAndSet(.includeRecaptchaScript(includeRecaptchaScript))
    }
    if let redirect = try container.decodeIfPresent(
      FirewallAction.RedirectAction?.self, forKey: .redirect)
    {
      try firewallActionOneofCheckAndSet(.redirect(redirect))
    }
    if let substitute = try container.decodeIfPresent(
      FirewallAction.SubstituteAction?.self, forKey: .substitute)
    {
      try firewallActionOneofCheckAndSet(.substitute(substitute))
    }
    if let setHeader = try container.decodeIfPresent(
      FirewallAction.SetHeaderAction?.self, forKey: .setHeader)
    {
      try firewallActionOneofCheckAndSet(.setHeader(setHeader))
    }
    self.firewallActionOneof = firewallActionOneof
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.firewallActionOneof {
      switch choice {
      case .allow(let value):
        try container.encode(value, forKey: .allow)
      case .block(let value):
        try container.encode(value, forKey: .block)
      case .includeRecaptchaScript(let value):
        try container.encode(value, forKey: .includeRecaptchaScript)
      case .redirect(let value):
        try container.encode(value, forKey: .redirect)
      case .substitute(let value):
        try container.encode(value, forKey: .substitute)
      case .setHeader(let value):
        try container.encode(value, forKey: .setHeader)
      }
    }
  }

  /// An allow action continues processing a request unimpeded.
  public struct AllowAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `AllowAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AllowAction().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FirewallAction.AllowAction"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A block action serves an HTTP error code a prevents the request from
  /// hitting the backend.
  public struct BlockAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `BlockAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BlockAction().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FirewallAction.BlockAction"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// An include reCAPTCHA script action involves injecting reCAPTCHA JavaScript
  /// code into the HTML returned by the site backend. This reCAPTCHA
  /// script is tasked with collecting user signals on the requested web page,
  /// issuing tokens as a cookie within the site domain, and enabling their
  /// utilization in subsequent page requests.
  public struct IncludeRecaptchaScriptAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `IncludeRecaptchaScriptAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IncludeRecaptchaScriptAction().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FirewallAction.IncludeRecaptchaScriptAction"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A redirect action returns a 307 (temporary redirect) response, pointing
  /// the user to a reCAPTCHA interstitial page to attach a token.
  public struct RedirectAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `RedirectAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RedirectAction().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FirewallAction.RedirectAction"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A substitute action transparently serves a different page than the one
  /// requested.
  public struct SubstituteAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The address to redirect to. The target is a relative path in
    /// the current host. Example: "/blog/404.html".
    public var path: Swift.String = Swift.String()

    /// Initialize a new instance of `SubstituteAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SubstituteAction().with { $0.path = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FirewallAction.SubstituteAction"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A set header action sets a header and forwards the request to the
  /// backend. This can be used to trigger custom protection implemented on the
  /// backend.
  public struct SetHeaderAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The header key to set in the request to the backend server.
    public var key: Swift.String = Swift.String()

    /// Optional. The header value to set in the request to the backend server.
    public var value: Swift.String = Swift.String()

    /// Initialize a new instance of `SetHeaderAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SetHeaderAction().with { $0.key = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FirewallAction.SetHeaderAction"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public enum OneOf_FirewallActionOneof: Codable, Equatable, Sendable {
    /// The user request did not match any policy and should be allowed
    /// access to the requested resource.
    indirect case allow(FirewallAction.AllowAction?)
    /// This action denies access to a given page. The user gets an HTTP
    /// error code.
    indirect case block(FirewallAction.BlockAction?)
    /// This action injects reCAPTCHA JavaScript code into the HTML page
    /// returned by the site backend.
    indirect case includeRecaptchaScript(FirewallAction.IncludeRecaptchaScriptAction?)
    /// This action redirects the request to a reCAPTCHA interstitial to
    /// attach a token.
    indirect case redirect(FirewallAction.RedirectAction?)
    /// This action transparently serves a different page to an offending
    /// user.
    indirect case substitute(FirewallAction.SubstituteAction?)
    /// This action sets a custom header but allow the request to continue
    /// to the customer backend.
    indirect case setHeader(FirewallAction.SetHeaderAction?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FirewallAction"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
