// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A FirewallPolicy represents a single matching pattern and resulting actions
/// to take.
public struct FirewallPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name for the FirewallPolicy in the format
  /// `projects/{project}/firewallpolicies/{firewallpolicy}`.
  public var name: Swift.String = Swift.String()

  /// Optional. A description of what this policy aims to achieve, for
  /// convenience purposes. The description can at most include 256 UTF-8
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Optional. The path for which this policy applies, specified as a glob
  /// pattern. For more information on glob, see the [manual
  /// page](https://man7.org/linux/man-pages/man7/glob.7.html).
  /// A path has a max length of 200 characters.
  public var path: Swift.String = Swift.String()

  /// Optional. A CEL (Common Expression Language) conditional expression that
  /// specifies if this policy applies to an incoming user request. If this
  /// condition evaluates to true and the requested path matched the path
  /// pattern, the associated actions should be executed by the caller. The
  /// condition string is checked for CEL syntax correctness on creation. For
  /// more information, see the [CEL spec](https://github.com/google/cel-spec)
  /// and its [language
  /// definition](https://github.com/google/cel-spec/blob/master/doc/langdef.md).
  /// A condition has a max length of 500 characters.
  public var condition: Swift.String = Swift.String()

  /// Optional. The actions that the caller should take regarding user access.
  /// There should be at most one terminal action. A terminal action is any
  /// action that forces a response, such as `AllowAction`,
  /// `BlockAction` or `SubstituteAction`.
  /// Zero or more non-terminal actions such as `SetHeader` might be
  /// specified. A single policy can contain up to 16 actions.
  public var actions: [FirewallAction] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FirewallPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FirewallPolicy().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let path = CodingKeys(stringValue: "path")
    static let condition = CodingKeys(stringValue: "condition")
    static let actions = CodingKeys(stringValue: "actions")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "path",
      "condition",
      "actions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
      self.path = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .condition) {
      self.condition = value
    }
    if let value = try container.decodeIfPresent([FirewallAction].self, forKey: .actions) {
      self.actions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.condition, forKey: .condition)
    try container.encode(self.actions, forKey: .actions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FirewallPolicy"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
