// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Assessment for Fraud Prevention.
public struct FraudPreventionAssessment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Probability of this transaction being fraudulent. Summarizes
  /// the combined risk of attack vectors below. Values are from 0.0 (lowest)
  /// to 1.0 (highest).
  public var transactionRisk: Swift.Float = Swift.Float()

  /// Output only. Reasons why the transaction is probably fraudulent and
  /// received a high transaction risk score.
  public var riskReasons: [FraudPreventionAssessment.RiskReason] = []

  /// Output only. Assessment of this transaction for risk of a stolen
  /// instrument.
  public var stolenInstrumentVerdict: FraudPreventionAssessment.StolenInstrumentVerdict? = nil

  /// Output only. Assessment of this transaction for risk of being part of a
  /// card testing attack.
  public var cardTestingVerdict: FraudPreventionAssessment.CardTestingVerdict? = nil

  /// Output only. Assessment of this transaction for behavioral trust.
  public var behavioralTrustVerdict: FraudPreventionAssessment.BehavioralTrustVerdict? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FraudPreventionAssessment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FraudPreventionAssessment().with { $0.transactionRisk = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let transactionRisk = CodingKeys(stringValue: "transactionRisk")
    static let riskReasons = CodingKeys(stringValue: "riskReasons")
    static let stolenInstrumentVerdict = CodingKeys(stringValue: "stolenInstrumentVerdict")
    static let cardTestingVerdict = CodingKeys(stringValue: "cardTestingVerdict")
    static let behavioralTrustVerdict = CodingKeys(stringValue: "behavioralTrustVerdict")

    static let _knownKeys: Set<Swift.String> = [
      "transactionRisk",
      "riskReasons",
      "stolenInstrumentVerdict",
      "cardTestingVerdict",
      "behavioralTrustVerdict",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .transactionRisk) {
      self.transactionRisk = value
    }
    if let value = try container.decodeIfPresent(
      [FraudPreventionAssessment.RiskReason].self, forKey: .riskReasons)
    {
      self.riskReasons = value
    }
    self.stolenInstrumentVerdict = try container.decodeIfPresent(
      FraudPreventionAssessment.StolenInstrumentVerdict.self, forKey: .stolenInstrumentVerdict)
    self.cardTestingVerdict = try container.decodeIfPresent(
      FraudPreventionAssessment.CardTestingVerdict.self, forKey: .cardTestingVerdict)
    self.behavioralTrustVerdict = try container.decodeIfPresent(
      FraudPreventionAssessment.BehavioralTrustVerdict.self, forKey: .behavioralTrustVerdict)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.transactionRisk, forKey: .transactionRisk)
    try container.encode(self.riskReasons, forKey: .riskReasons)
    try container.encodeIfPresent(self.stolenInstrumentVerdict, forKey: .stolenInstrumentVerdict)
    try container.encodeIfPresent(self.cardTestingVerdict, forKey: .cardTestingVerdict)
    try container.encodeIfPresent(self.behavioralTrustVerdict, forKey: .behavioralTrustVerdict)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Risk reasons applicable to the Fraud Prevention assessment.
  public struct RiskReason: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Risk reasons applicable to the Fraud Prevention assessment.
    public var reason: FraudPreventionAssessment.RiskReason.Reason = FraudPreventionAssessment
      .RiskReason.Reason()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RiskReason`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RiskReason().with { $0.reason = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let reason = CodingKeys(stringValue: "reason")

      static let _knownKeys: Set<Swift.String> = [
        "reason"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        FraudPreventionAssessment.RiskReason.Reason.self, forKey: .reason)
      {
        self.reason = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.reason, forKey: .reason)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Risk reasons applicable to the Fraud Prevention assessment. New risk
    /// reasons will be added over time.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum Reason: Codable, Equatable, Sendable {
      /// Default unspecified type.
      case unspecified
      /// A suspiciously high number of recent transactions have used identifiers
      /// present in this transaction.
      case highTransactionVelocity
      /// User is cycling through a suspiciously large number of identifiers,
      /// suggesting enumeration or validation attacks within a potential fraud
      /// network.
      case excessiveEnumerationPattern
      /// User has a short history or no history in the reCAPTCHA network,
      /// suggesting the possibility of synthetic identity generation.
      case shortIdentityHistory
      /// Identifiers used in this transaction originate from an unusual or
      /// conflicting set of geolocations.
      case geolocationDiscrepancy
      /// This transaction is linked to a cluster of known fraudulent activity.
      case associatedWithFraudCluster
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .highTransactionVelocity: return 1
        case .excessiveEnumerationPattern: return 2
        case .shortIdentityHistory: return 3
        case .geolocationDiscrepancy: return 4
        case .associatedWithFraudCluster: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "REASON_UNSPECIFIED"
        case .highTransactionVelocity: return "HIGH_TRANSACTION_VELOCITY"
        case .excessiveEnumerationPattern: return "EXCESSIVE_ENUMERATION_PATTERN"
        case .shortIdentityHistory: return "SHORT_IDENTITY_HISTORY"
        case .geolocationDiscrepancy: return "GEOLOCATION_DISCREPANCY"
        case .associatedWithFraudCluster: return "ASSOCIATED_WITH_FRAUD_CLUSTER"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Reason/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "REASON_UNSPECIFIED": self = .unspecified
        case "HIGH_TRANSACTION_VELOCITY": self = .highTransactionVelocity
        case "EXCESSIVE_ENUMERATION_PATTERN": self = .excessiveEnumerationPattern
        case "SHORT_IDENTITY_HISTORY": self = .shortIdentityHistory
        case "GEOLOCATION_DISCREPANCY": self = .geolocationDiscrepancy
        case "ASSOCIATED_WITH_FRAUD_CLUSTER": self = .associatedWithFraudCluster
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Reason/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .highTransactionVelocity
        case 2: self = .excessiveEnumerationPattern
        case 3: self = .shortIdentityHistory
        case 4: self = .geolocationDiscrepancy
        case 5: self = .associatedWithFraudCluster
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("REASON_UNSPECIFIED")
        case .highTransactionVelocity: return try container.encode("HIGH_TRANSACTION_VELOCITY")
        case .excessiveEnumerationPattern:
          return try container.encode("EXCESSIVE_ENUMERATION_PATTERN")
        case .shortIdentityHistory: return try container.encode("SHORT_IDENTITY_HISTORY")
        case .geolocationDiscrepancy: return try container.encode("GEOLOCATION_DISCREPANCY")
        case .associatedWithFraudCluster:
          return try container.encode("ASSOCIATED_WITH_FRAUD_CLUSTER")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.RiskReason"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information about stolen instrument fraud, where the user is not the
  /// legitimate owner of the instrument being used for the purchase.
  public struct StolenInstrumentVerdict: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Probability of this transaction being executed with a stolen
    /// instrument. Values are from 0.0 (lowest) to 1.0 (highest).
    public var risk: Swift.Float = Swift.Float()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `StolenInstrumentVerdict`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StolenInstrumentVerdict().with { $0.risk = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let risk = CodingKeys(stringValue: "risk")

      static let _knownKeys: Set<Swift.String> = [
        "risk"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .risk) {
        self.risk = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.risk, forKey: .risk)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.StolenInstrumentVerdict"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information about card testing fraud, where an adversary is testing
  /// fraudulently obtained cards or brute forcing their details.
  public struct CardTestingVerdict: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Probability of this transaction attempt being part of a card
    /// testing attack. Values are from 0.0 (lowest) to 1.0 (highest).
    public var risk: Swift.Float = Swift.Float()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CardTestingVerdict`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CardTestingVerdict().with { $0.risk = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let risk = CodingKeys(stringValue: "risk")

      static let _knownKeys: Set<Swift.String> = [
        "risk"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .risk) {
        self.risk = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.risk, forKey: .risk)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.CardTestingVerdict"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information about behavioral trust of the transaction.
  public struct BehavioralTrustVerdict: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Probability of this transaction attempt being executed in a
    /// behaviorally trustworthy way. Values are from 0.0 (lowest) to 1.0
    /// (highest).
    public var trust: Swift.Float = Swift.Float()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `BehavioralTrustVerdict`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BehavioralTrustVerdict().with { $0.trust = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let trust = CodingKeys(stringValue: "trust")

      static let _knownKeys: Set<Swift.String> = [
        "trust"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .trust) {
        self.trust = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.trust, forKey: .trust)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.BehavioralTrustVerdict"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
