// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Fraud signals describing users and cards involved in the transaction.
public struct FraudSignals: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Signals describing the end user in this transaction.
  public var userSignals: FraudSignals.UserSignals? = nil

  /// Output only. Signals describing the payment card or cards used in this
  /// transaction.
  public var cardSignals: FraudSignals.CardSignals? = nil

  /// Initialize a new instance of `FraudSignals`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FraudSignals().with { $0.userSignals = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Signals describing the user involved in this transaction.
  public struct UserSignals: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. This user (based on email, phone, and other identifiers) has
    /// been seen on the internet for at least this number of days.
    public var activeDaysLowerBound: Swift.Int32 = Swift.Int32()

    /// Output only. Likelihood (from 0.0 to 1.0) this user includes synthetic
    /// components in their identity, such as a randomly generated email address,
    /// temporary phone number, or fake shipping address.
    public var syntheticRisk: Swift.Float = Swift.Float()

    /// Initialize a new instance of `UserSignals`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UserSignals().with { $0.activeDaysLowerBound = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FraudSignals.UserSignals"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Signals describing the payment card used in this transaction.
  public struct CardSignals: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. The labels for the payment card in this transaction.
    public var cardLabels: [FraudSignals.CardSignals.CardLabel] = []

    /// Initialize a new instance of `CardSignals`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CardSignals().with { $0.cardLabels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Risk labels describing the card being assessed, such as its funding
    /// mechanism.
    /// Ensure that applications can handle values not explicitly listed.
    public enum CardLabel: Codable, Equatable, Sendable {
      /// No label specified.
      case unspecified
      /// This card has been detected as prepaid.
      case prepaid
      /// This card has been detected as virtual, such as a card number generated
      /// for a single transaction or merchant.
      case virtual
      /// This card has been detected as being used in an unexpected geographic
      /// location.
      case unexpectedLocation
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .prepaid: return 1
        case .virtual: return 2
        case .unexpectedLocation: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CARD_LABEL_UNSPECIFIED"
        case .prepaid: return "PREPAID"
        case .virtual: return "VIRTUAL"
        case .unexpectedLocation: return "UNEXPECTED_LOCATION"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CardLabel/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CARD_LABEL_UNSPECIFIED": self = .unspecified
        case "PREPAID": self = .prepaid
        case "VIRTUAL": self = .virtual
        case "UNEXPECTED_LOCATION": self = .unexpectedLocation
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CardLabel/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .prepaid
        case 2: self = .virtual
        case 3: self = .unexpectedLocation
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .prepaid: return try container.encode(1)
        case .virtual: return try container.encode(2)
        case .unexpectedLocation: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FraudSignals.CardSignals"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.FraudSignals"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
