// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Settings specific to keys that can be used by iOS apps.
public struct IOSKeySettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. If set to true, allowed_bundle_ids are not enforced.
  public var allowAllBundleIds: Swift.Bool = Swift.Bool()

  /// Optional. iOS bundle IDs of apps allowed to use the key.
  /// Example: 'com.companyname.productname.appname'
  /// Each key supports a maximum of 250 bundle IDs. To use a key on more
  /// apps, set `allow_all_bundle_ids` to true. When this is set, you
  /// are responsible for validating the bundle id by checking the
  /// `token_properties.ios_bundle_id` field in each assessment response
  /// against your list of allowed bundle IDs.
  public var allowedBundleIds: [Swift.String] = []

  /// Optional. Apple Developer account details for the app that is protected by
  /// the reCAPTCHA Key. reCAPTCHA leverages platform-specific checks like Apple
  /// App Attest and Apple DeviceCheck to protect your app from abuse. Providing
  /// these fields allows reCAPTCHA to get a better assessment of the integrity
  /// of your app.
  public var appleDeveloperId: AppleDeveloperId? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `IOSKeySettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IOSKeySettings().with { $0.allowAllBundleIds = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let allowAllBundleIds = CodingKeys(stringValue: "allowAllBundleIds")
    static let allowedBundleIds = CodingKeys(stringValue: "allowedBundleIds")
    static let appleDeveloperId = CodingKeys(stringValue: "appleDeveloperId")

    static let _knownKeys: Set<Swift.String> = [
      "allowAllBundleIds",
      "allowedBundleIds",
      "appleDeveloperId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowAllBundleIds) {
      self.allowAllBundleIds = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .allowedBundleIds) {
      self.allowedBundleIds = value
    }
    self.appleDeveloperId = try container.decodeIfPresent(
      AppleDeveloperId.self, forKey: .appleDeveloperId)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.allowAllBundleIds, forKey: .allowAllBundleIds)
    try container.encode(self.allowedBundleIds, forKey: .allowedBundleIds)
    try container.encodeIfPresent(self.appleDeveloperId, forKey: .appleDeveloperId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.IOSKeySettings"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
