// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Information about the IP or IP range override.
public struct IpOverrideData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The IP address to override (can be IPv4, IPv6 or CIDR).
  /// The IP override must be a valid IPv4 or IPv6 address, or a CIDR range.
  /// The IP override must be a public IP address.
  /// Example of IPv4: 168.192.5.6
  /// Example of IPv6: 2001:0000:130F:0000:0000:09C0:876A:130B
  /// Example of IPv4 with CIDR: 168.192.5.0/24
  /// Example of IPv6 with CIDR: 2001:0DB8:1234::/48
  public var ip: Swift.String = Swift.String()

  /// Required. Describes the type of IP override.
  public var overrideType: IpOverrideData.OverrideType = IpOverrideData.OverrideType()

  /// Initialize a new instance of `IpOverrideData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IpOverrideData().with { $0.ip = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Enum that represents the type of IP override.
  /// Ensure that applications can handle values not explicitly listed.
  public enum OverrideType: Codable, Equatable, Sendable {
    /// Default override type that indicates this enum hasn't been specified.
    case unspecified
    /// Allowlist the IP address; i.e. give a `risk_analysis.score` of 0.9 for
    /// all valid assessments.
    case allow
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .allow: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OVERRIDE_TYPE_UNSPECIFIED"
      case .allow: return "ALLOW"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OverrideType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OVERRIDE_TYPE_UNSPECIFIED": self = .unspecified
      case "ALLOW": self = .allow
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OverrideType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .allow
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .allow: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.IpOverrideData"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
