// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A key used to identify and configure applications (web and/or mobile) that
/// use reCAPTCHA Enterprise.
public struct Key: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name for the Key in the format
  /// `projects/{project}/keys/{key}`.
  public var name: Swift.String = Swift.String()

  /// Required. Human-readable display name of this key. Modifiable by user.
  public var displayName: Swift.String = Swift.String()

  /// Optional. See [Creating and managing labels]
  /// (https://cloud.google.com/recaptcha/docs/labels).
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The timestamp corresponding to the creation of this key.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Optional. Options for user acceptance testing.
  public var testingOptions: TestingOptions? = nil

  /// Optional. Settings for Web Application Firewall (WAF).
  public var wafSettings: WafSettings? = nil

  /// Platform-specific settings for this key. The key can only be used on a
  /// platform for which the settings are enabled.
  public var platformSettings: OneOf_PlatformSettings? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Key`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Key().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let webSettings = CodingKeys(stringValue: "webSettings")
    static let androidSettings = CodingKeys(stringValue: "androidSettings")
    static let iosSettings = CodingKeys(stringValue: "iosSettings")
    static let expressSettings = CodingKeys(stringValue: "expressSettings")
    static let universalSettings = CodingKeys(stringValue: "universalSettings")
    static let labels = CodingKeys(stringValue: "labels")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let testingOptions = CodingKeys(stringValue: "testingOptions")
    static let wafSettings = CodingKeys(stringValue: "wafSettings")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "webSettings",
      "androidSettings",
      "iosSettings",
      "expressSettings",
      "universalSettings",
      "labels",
      "createTime",
      "testingOptions",
      "wafSettings",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.testingOptions = try container.decodeIfPresent(
      TestingOptions.self, forKey: .testingOptions)
    self.wafSettings = try container.decodeIfPresent(WafSettings.self, forKey: .wafSettings)

    var platformSettings: OneOf_PlatformSettings? = nil
    let platformSettingsCheckAndSet = {
      if platformSettings != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'platformSettings'"))
      }
      platformSettings = $0
    }
    if let webSettings = try container.decodeIfPresent(WebKeySettings?.self, forKey: .webSettings) {
      try platformSettingsCheckAndSet(.webSettings(webSettings))
    }
    if let androidSettings = try container.decodeIfPresent(
      AndroidKeySettings?.self, forKey: .androidSettings)
    {
      try platformSettingsCheckAndSet(.androidSettings(androidSettings))
    }
    if let iosSettings = try container.decodeIfPresent(IOSKeySettings?.self, forKey: .iosSettings) {
      try platformSettingsCheckAndSet(.iosSettings(iosSettings))
    }
    if let expressSettings = try container.decodeIfPresent(
      ExpressKeySettings?.self, forKey: .expressSettings)
    {
      try platformSettingsCheckAndSet(.expressSettings(expressSettings))
    }
    if let universalSettings = try container.decodeIfPresent(
      UniversalKeySettings?.self, forKey: .universalSettings)
    {
      try platformSettingsCheckAndSet(.universalSettings(universalSettings))
    }
    self.platformSettings = platformSettings
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.testingOptions, forKey: .testingOptions)
    try container.encodeIfPresent(self.wafSettings, forKey: .wafSettings)

    if let choice = self.platformSettings {
      switch choice {
      case .webSettings(let value):
        try container.encode(value, forKey: .webSettings)
      case .androidSettings(let value):
        try container.encode(value, forKey: .androidSettings)
      case .iosSettings(let value):
        try container.encode(value, forKey: .iosSettings)
      case .expressSettings(let value):
        try container.encode(value, forKey: .expressSettings)
      case .universalSettings(let value):
        try container.encode(value, forKey: .universalSettings)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Platform-specific settings for this key. The key can only be used on a
  /// platform for which the settings are enabled.
  public enum OneOf_PlatformSettings: Codable, Equatable, Sendable {
    /// Settings for keys that can be used by websites.
    indirect case webSettings(WebKeySettings?)
    /// Settings for keys that can be used by Android apps.
    indirect case androidSettings(AndroidKeySettings?)
    /// Settings for keys that can be used by iOS apps.
    indirect case iosSettings(IOSKeySettings?)
    /// Settings for keys that can be used by reCAPTCHA Express.
    indirect case expressSettings(ExpressKeySettings?)
    /// Settings for keys that are configured through their Policy.
    indirect case universalSettings(UniversalKeySettings?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.Key"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
