// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Metrics for a single Key.
public struct Metrics: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The name of the metrics, in the format
  /// `projects/{project}/keys/{key}/metrics`.
  public var name: Swift.String = Swift.String()

  /// Inclusive start time aligned to a day in the America/Los_Angeles (Pacific)
  /// timezone.
  public var startTime: GoogleWKT.Timestamp? = nil

  /// Metrics are continuous and in order by dates, and in the granularity
  /// of day. All Key types should have score-based data.
  public var scoreMetrics: [ScoreMetrics] = []

  /// Metrics are continuous and in order by dates, and in the granularity
  /// of day. Only challenge-based keys (CHECKBOX, INVISIBLE) have
  /// challenge-based data.
  public var challengeMetrics: [ChallengeMetrics] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Metrics`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Metrics().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let scoreMetrics = CodingKeys(stringValue: "scoreMetrics")
    static let challengeMetrics = CodingKeys(stringValue: "challengeMetrics")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "startTime",
      "scoreMetrics",
      "challengeMetrics",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
    if let value = try container.decodeIfPresent([ScoreMetrics].self, forKey: .scoreMetrics) {
      self.scoreMetrics = value
    }
    if let value = try container.decodeIfPresent([ChallengeMetrics].self, forKey: .challengeMetrics)
    {
      self.challengeMetrics = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encode(self.scoreMetrics, forKey: .scoreMetrics)
    try container.encode(self.challengeMetrics, forKey: .challengeMetrics)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.Metrics"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
