// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The migrate key request message.
public struct MigrateKeyRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the key to be migrated, in the format
  /// `projects/{project}/keys/{key}`.
  public var name: Swift.String = Swift.String()

  /// Optional. If true, skips the billing check.
  /// A reCAPTCHA Enterprise key or migrated key behaves differently than a
  /// reCAPTCHA (non-Enterprise version) key when you reach a quota limit (see
  /// https://docs.cloud.google.com/recaptcha/quotas#quota_limit). To avoid
  /// any disruption of your usage, we check that a billing account is present.
  /// If your usage of reCAPTCHA is under the free quota, you can safely skip the
  /// billing check and proceed with the migration. See
  /// https://cloud.google.com/recaptcha/docs/billing-information.
  public var skipBillingCheck: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `MigrateKeyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MigrateKeyRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.MigrateKeyRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
