// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details on a phone authentication event
public struct PhoneAuthenticationEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Phone number in E.164 format for which a multi-factor
  /// authentication challenge was initiated, succeeded, or failed.
  public var phoneNumber: Swift.String = Swift.String()

  /// Optional. The time at which the multi-factor authentication event
  /// (challenge or verification) occurred.
  public var eventTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `PhoneAuthenticationEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PhoneAuthenticationEvent().with { $0.phoneNumber = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.PhoneAuthenticationEvent"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
