// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configuration for API endpoints to protect with reCAPTCHA.
public struct ProtectedEndpointGroup: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. List of API endpoints to automatically protect with reCAPTCHA. If
  /// any of these endpoints is invoked from a page where a key bound to this
  /// policy is installed, a reCAPTCHA token is automatically generated and
  /// attached to the request. If multiple protected endpoints match a given API
  /// endpoint, the first one in the list is used.
  public var protectedEndpoints: [ProtectedEndpoint] = []

  /// Initialize a new instance of `ProtectedEndpointGroup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProtectedEndpointGroup().with { $0.protectedEndpoints = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.ProtectedEndpointGroup"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
