// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for an API endpoint to protect with reCAPTCHA.
public struct ProtectedEndpoint: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. URI path of the API endpoint to protect. Must start with '/'.
  /// Supports glob characters '*' to match a single path segment and '**' to
  /// match multiple path segments. Standalone root catch-alls ('/*' and '/**')
  /// are invalid because it can negatively impact performance to trigger
  /// reCAPTCHA on every single request to your backend.
  ///
  /// Matching is evaluated against the URL path only (domain, scheme, and query
  /// parameters are ignored).
  ///
  /// Examples:
  /// - `/login` matches `/login`, `https://example.com/login`, and
  /// `/login?query=1`, but not `/login/step1`.
  /// - `/products/*` matches `/products/123`, but not `/products/123/456`.
  /// - `/content/**` matches `/content/articles/2024/01/01`.
  public var path: Swift.String = Swift.String()

  /// Required. Action name to be used for token generation for this endpoint.
  /// The action name can only contain alphanumeric characters, slashes, and
  /// underscores.
  public var action: Swift.String = Swift.String()

  /// Initialize a new instance of `ProtectedEndpoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProtectedEndpoint().with { $0.path = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.ProtectedEndpoint"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
