// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Risk analysis result for an event.
public struct RiskAnalysis: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Legitimate event score from 0.0 to 1.0.
  /// (1.0 means very likely legitimate traffic while 0.0 means very likely
  /// non-legitimate traffic).
  public var score: Swift.Float = Swift.Float()

  /// Output only. Reasons contributing to the risk analysis verdict.
  public var reasons: [RiskAnalysis.ClassificationReason] = []

  /// Output only. Additional reasons contributing to the risk analysis verdict.
  /// These reasons are available to Enterprise tier projects only. Contact sales
  /// for more information.
  /// The set of reasons is subject to change.
  public var extendedVerdictReasons: [Swift.String] = []

  /// Output only. Type of the last challenge presented to the user for
  /// Universal, `POLICY_BASED_CHALLENGE` and `INVISIBLE` keys. The field is only
  /// set when a challenge was presented to the user.
  public var lastChallengeType: ChallengeType = ChallengeType()

  /// Output only. Challenge information for Universal, `POLICY_BASED_CHALLENGE`
  /// and `INVISIBLE` keys.
  public var challenge: RiskAnalysis.Challenge = RiskAnalysis.Challenge()

  /// Output only. Bots with identities that have been verified by reCAPTCHA and
  /// detected in the event.
  public var verifiedBots: [Bot] = []

  /// Initialize a new instance of `RiskAnalysis`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RiskAnalysis().with { $0.score = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Reasons contributing to the risk analysis verdict.
  /// Ensure that applications can handle values not explicitly listed.
  public enum ClassificationReason: Codable, Equatable, Sendable {
    /// Default unspecified type.
    case unspecified
    /// Interactions matched the behavior of an automated agent.
    case automation
    /// The event originated from an illegitimate environment.
    case unexpectedEnvironment
    /// Traffic volume from the event source is higher than normal.
    case tooMuchTraffic
    /// Interactions with the site were significantly different than expected
    /// patterns.
    case unexpectedUsagePatterns
    /// Too little traffic has been received from this site thus far to generate
    /// quality risk analysis.
    case lowConfidenceScore
    /// Deprecated: Use
    /// [FraudPreventionAssessment.transaction_risk][google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.transaction_risk]
    /// and
    /// [FraudPreventionAssessment.RiskReason.Reason.EXCESSIVE_ENUMERATION_PATTERN][google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.RiskReason.Reason.EXCESSIVE_ENUMERATION_PATTERN]
    /// instead.
    ///
    /// [google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.RiskReason.Reason.EXCESSIVE_ENUMERATION_PATTERN]: <doc:FraudPreventionAssessment/RiskReason/Reason/excessiveEnumerationPattern>
    /// [google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.transaction_risk]: <doc:FraudPreventionAssessment/transactionRisk>
    @available(*, deprecated)
    case suspectedCarding
    /// Deprecated: Use
    /// [FraudPreventionAssessment.transaction_risk][google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.transaction_risk]
    /// and
    /// [FraudPreventionAssessment.RiskReason.Reason.ASSOCIATED_WITH_FRAUD_CLUSTER][google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.RiskReason.Reason.ASSOCIATED_WITH_FRAUD_CLUSTER]
    /// instead.
    ///
    /// [google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.RiskReason.Reason.ASSOCIATED_WITH_FRAUD_CLUSTER]: <doc:FraudPreventionAssessment/RiskReason/Reason/associatedWithFraudCluster>
    /// [google.cloud.recaptchaenterprise.v1.FraudPreventionAssessment.transaction_risk]: <doc:FraudPreventionAssessment/transactionRisk>
    @available(*, deprecated)
    case suspectedChargeback
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .automation: return 1
      case .unexpectedEnvironment: return 2
      case .tooMuchTraffic: return 3
      case .unexpectedUsagePatterns: return 4
      case .lowConfidenceScore: return 5
      case .suspectedCarding: return 6
      case .suspectedChargeback: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLASSIFICATION_REASON_UNSPECIFIED"
      case .automation: return "AUTOMATION"
      case .unexpectedEnvironment: return "UNEXPECTED_ENVIRONMENT"
      case .tooMuchTraffic: return "TOO_MUCH_TRAFFIC"
      case .unexpectedUsagePatterns: return "UNEXPECTED_USAGE_PATTERNS"
      case .lowConfidenceScore: return "LOW_CONFIDENCE_SCORE"
      case .suspectedCarding: return "SUSPECTED_CARDING"
      case .suspectedChargeback: return "SUSPECTED_CHARGEBACK"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ClassificationReason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLASSIFICATION_REASON_UNSPECIFIED": self = .unspecified
      case "AUTOMATION": self = .automation
      case "UNEXPECTED_ENVIRONMENT": self = .unexpectedEnvironment
      case "TOO_MUCH_TRAFFIC": self = .tooMuchTraffic
      case "UNEXPECTED_USAGE_PATTERNS": self = .unexpectedUsagePatterns
      case "LOW_CONFIDENCE_SCORE": self = .lowConfidenceScore
      case "SUSPECTED_CARDING": self = .suspectedCarding
      case "SUSPECTED_CHARGEBACK": self = .suspectedChargeback
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ClassificationReason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .automation
      case 2: self = .unexpectedEnvironment
      case 3: self = .tooMuchTraffic
      case 4: self = .unexpectedUsagePatterns
      case 5: self = .lowConfidenceScore
      case 6: self = .suspectedCarding
      case 7: self = .suspectedChargeback
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .automation: return try container.encode(1)
      case .unexpectedEnvironment: return try container.encode(2)
      case .tooMuchTraffic: return try container.encode(3)
      case .unexpectedUsagePatterns: return try container.encode(4)
      case .lowConfidenceScore: return try container.encode(5)
      case .suspectedCarding: return try container.encode(6)
      case .suspectedChargeback: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Challenge information for Universal, `POLICY_BASED_CHALLENGE` and
  /// `INVISIBLE` keys. Ensure that applications can handle values not explicitly
  /// listed.
  public enum Challenge: Codable, Equatable, Sendable {
    /// Default unspecified type.
    case unspecified
    /// No challenge was presented for solving.
    case nocaptcha
    /// A solution was submitted that was correct.
    case passed
    /// A solution was submitted that was incorrect or otherwise
    /// deemed suspicious.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .nocaptcha: return 1
      case .passed: return 2
      case .failed: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CHALLENGE_UNSPECIFIED"
      case .nocaptcha: return "NOCAPTCHA"
      case .passed: return "PASSED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Challenge/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CHALLENGE_UNSPECIFIED": self = .unspecified
      case "NOCAPTCHA": self = .nocaptcha
      case "PASSED": self = .passed
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Challenge/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .nocaptcha
      case 2: self = .passed
      case 3: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .nocaptcha: return try container.encode(1)
      case .passed: return try container.encode(2)
      case .failed: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.RiskAnalysis"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
