// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The request message to search related account group memberships.
public struct SearchRelatedAccountGroupMembershipsRequest: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Required. The name of the project to search related account group
  /// memberships from. Specify the project name in the following format:
  /// `projects/{project}`.
  public var project: Swift.String = Swift.String()

  /// Optional. The unique stable account identifier used to search connections.
  /// The identifier should correspond to an `account_id` provided in a previous
  /// `CreateAssessment` or `AnnotateAssessment` call. Either hashed_account_id
  /// or account_id must be set, but not both.
  public var accountId: Swift.String = Swift.String()

  /// Optional. Deprecated: use `account_id` instead.
  /// The unique stable hashed account identifier used to search connections. The
  /// identifier should correspond to a `hashed_account_id` provided in a
  /// previous `CreateAssessment` or `AnnotateAssessment` call. Either
  /// hashed_account_id or account_id must be set, but not both.
  @available(*, deprecated)
  public var hashedAccountId: Foundation.Data = Foundation.Data()

  /// Optional. The maximum number of groups to return. The service might return
  /// fewer than this value. If unspecified, at most 50 groups are returned. The
  /// maximum value is 1000; values above 1000 are coerced to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous
  /// `SearchRelatedAccountGroupMemberships` call. Provide this to retrieve the
  /// subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// `SearchRelatedAccountGroupMemberships` must match the call that provided
  /// the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `SearchRelatedAccountGroupMembershipsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchRelatedAccountGroupMembershipsRequest().with { $0.project = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.recaptchaenterprise.v1.SearchRelatedAccountGroupMembershipsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
