// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Properties of the provided event token.
public struct TokenProperties: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Indicates whether the provided user response token is valid.
  /// If `false`, the token is invalid, either because the user failed the
  /// challenge or for a reason provided in the `invalid_reason` field.
  public var valid: Swift.Bool = Swift.Bool()

  /// Output only. Reason associated with the response when valid = false.
  public var invalidReason: TokenProperties.InvalidReason = TokenProperties.InvalidReason()

  /// Output only. The timestamp corresponding to the generation of the token.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The hostname of the page on which the token was generated (Web
  /// keys only).
  public var hostname: Swift.String = Swift.String()

  /// Output only. The name of the Android package with which the token was
  /// generated (Android keys only).
  public var androidPackageName: Swift.String = Swift.String()

  /// Output only. The ID of the iOS bundle with which the token was generated
  /// (iOS keys only).
  public var iosBundleId: Swift.String = Swift.String()

  /// Output only. Action name provided at token generation.
  public var action: Swift.String = Swift.String()

  /// Initialize a new instance of `TokenProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TokenProperties().with { $0.valid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Enum that represents the types of invalid token reasons.
  /// Ensure that applications can handle values not explicitly listed.
  public enum InvalidReason: Codable, Equatable, Sendable {
    /// Default unspecified type.
    case unspecified
    /// If the failure reason was not accounted for.
    case unknownInvalidReason
    /// The provided user verification token was malformed.
    case malformed
    /// The user verification token had expired.
    case expired
    /// The user verification had already been seen.
    case dupe
    /// The user verification token was not present.
    case missing
    /// A retriable error (such as network failure) occurred on the browser.
    /// Could easily be simulated by an attacker.
    case browserError
    /// The action provided at token generation was different than
    /// the `expected_action` in the assessment request. The comparison is
    /// case-insensitive. This reason can only be returned if all of the
    /// following are true:
    ///
    ///   - your `site_key` has the POLICY_BASED_CHALLENGE integration type
    ///   - you set an action score threshold higher than 0.0
    ///   - you provided a non-empty `expected_action`
    case unexpectedAction
    /// The key used to generate the token does not match the `site_key`.
    case keyMismatch
    /// The domain of the page on which the token was generated does not match
    /// the `allowed_domains` configured in the `site_key`.
    case domainMismatch
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .unknownInvalidReason: return 1
      case .malformed: return 2
      case .expired: return 3
      case .dupe: return 4
      case .missing: return 5
      case .browserError: return 6
      case .unexpectedAction: return 7
      case .keyMismatch: return 8
      case .domainMismatch: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INVALID_REASON_UNSPECIFIED"
      case .unknownInvalidReason: return "UNKNOWN_INVALID_REASON"
      case .malformed: return "MALFORMED"
      case .expired: return "EXPIRED"
      case .dupe: return "DUPE"
      case .missing: return "MISSING"
      case .browserError: return "BROWSER_ERROR"
      case .unexpectedAction: return "UNEXPECTED_ACTION"
      case .keyMismatch: return "KEY_MISMATCH"
      case .domainMismatch: return "DOMAIN_MISMATCH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InvalidReason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INVALID_REASON_UNSPECIFIED": self = .unspecified
      case "UNKNOWN_INVALID_REASON": self = .unknownInvalidReason
      case "MALFORMED": self = .malformed
      case "EXPIRED": self = .expired
      case "DUPE": self = .dupe
      case "MISSING": self = .missing
      case "BROWSER_ERROR": self = .browserError
      case "UNEXPECTED_ACTION": self = .unexpectedAction
      case "KEY_MISMATCH": self = .keyMismatch
      case "DOMAIN_MISMATCH": self = .domainMismatch
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InvalidReason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .unknownInvalidReason
      case 2: self = .malformed
      case 3: self = .expired
      case 4: self = .dupe
      case 5: self = .missing
      case 6: self = .browserError
      case 7: self = .unexpectedAction
      case 8: self = .keyMismatch
      case 9: self = .domainMismatch
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .unknownInvalidReason: return try container.encode(1)
      case .malformed: return try container.encode(2)
      case .expired: return try container.encode(3)
      case .dupe: return try container.encode(4)
      case .missing: return try container.encode(5)
      case .browserError: return try container.encode(6)
      case .unexpectedAction: return try container.encode(7)
      case .keyMismatch: return try container.encode(8)
      case .domainMismatch: return try container.encode(9)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.TokenProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
