// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Transaction data associated with a payment protected by reCAPTCHA Enterprise.
public struct TransactionData: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Unique identifier for the transaction. This custom identifier can be used
  /// to reference this transaction in the future, for example, labeling a refund
  /// or chargeback event. Two attempts at the same transaction should use the
  /// same transaction id.
  public var transactionId: Swift.String? = nil

  /// Optional. The payment method for the transaction. The allowed values are:
  ///
  /// * credit-card
  /// * debit-card
  /// * gift-card
  /// * processor-{name} (If a third-party is used, for example,
  /// processor-paypal)
  /// * custom-{name} (If an alternative method is used, for example,
  /// custom-crypto)
  public var paymentMethod: Swift.String = Swift.String()

  /// Optional. The Bank Identification Number - generally the first 6 or 8
  /// digits of the card.
  public var cardBin: Swift.String = Swift.String()

  /// Optional. The last four digits of the card.
  public var cardLastFour: Swift.String = Swift.String()

  /// Optional. The currency code in ISO-4217 format.
  public var currencyCode: Swift.String = Swift.String()

  /// Optional. The decimal value of the transaction in the specified currency.
  public var value: Swift.Double = Swift.Double()

  /// Optional. The value of shipping in the specified currency. 0 for free or no
  /// shipping.
  public var shippingValue: Swift.Double = Swift.Double()

  /// Optional. Destination address if this transaction involves shipping a
  /// physical item.
  public var shippingAddress: TransactionData.Address? = nil

  /// Optional. Address associated with the payment method when applicable.
  public var billingAddress: TransactionData.Address? = nil

  /// Optional. Information about the user paying/initiating the transaction.
  public var user: TransactionData.User? = nil

  /// Optional. Information about the user or users fulfilling the transaction.
  public var merchants: [TransactionData.User] = []

  /// Optional. Items purchased in this transaction.
  public var items: [TransactionData.Item] = []

  /// Optional. Information about the payment gateway's response to the
  /// transaction.
  public var gatewayInfo: TransactionData.GatewayInfo? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransactionData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransactionData().with { $0.transactionId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let transactionId = CodingKeys(stringValue: "transactionId")
    static let paymentMethod = CodingKeys(stringValue: "paymentMethod")
    static let cardBin = CodingKeys(stringValue: "cardBin")
    static let cardLastFour = CodingKeys(stringValue: "cardLastFour")
    static let currencyCode = CodingKeys(stringValue: "currencyCode")
    static let value = CodingKeys(stringValue: "value")
    static let shippingValue = CodingKeys(stringValue: "shippingValue")
    static let shippingAddress = CodingKeys(stringValue: "shippingAddress")
    static let billingAddress = CodingKeys(stringValue: "billingAddress")
    static let user = CodingKeys(stringValue: "user")
    static let merchants = CodingKeys(stringValue: "merchants")
    static let items = CodingKeys(stringValue: "items")
    static let gatewayInfo = CodingKeys(stringValue: "gatewayInfo")

    static let _knownKeys: Set<Swift.String> = [
      "transactionId",
      "paymentMethod",
      "cardBin",
      "cardLastFour",
      "currencyCode",
      "value",
      "shippingValue",
      "shippingAddress",
      "billingAddress",
      "user",
      "merchants",
      "items",
      "gatewayInfo",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.transactionId = try container.decodeIfPresent(Swift.String.self, forKey: .transactionId)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .paymentMethod) {
      self.paymentMethod = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cardBin) {
      self.cardBin = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cardLastFour) {
      self.cardLastFour = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .currencyCode) {
      self.currencyCode = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .value) {
      self.value = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .shippingValue) {
      self.shippingValue = value
    }
    self.shippingAddress = try container.decodeIfPresent(
      TransactionData.Address.self, forKey: .shippingAddress)
    self.billingAddress = try container.decodeIfPresent(
      TransactionData.Address.self, forKey: .billingAddress)
    self.user = try container.decodeIfPresent(TransactionData.User.self, forKey: .user)
    if let value = try container.decodeIfPresent([TransactionData.User].self, forKey: .merchants) {
      self.merchants = value
    }
    if let value = try container.decodeIfPresent([TransactionData.Item].self, forKey: .items) {
      self.items = value
    }
    self.gatewayInfo = try container.decodeIfPresent(
      TransactionData.GatewayInfo.self, forKey: .gatewayInfo)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.transactionId, forKey: .transactionId)
    try container.encode(self.paymentMethod, forKey: .paymentMethod)
    try container.encode(self.cardBin, forKey: .cardBin)
    try container.encode(self.cardLastFour, forKey: .cardLastFour)
    try container.encode(self.currencyCode, forKey: .currencyCode)
    try container.encode(self.value, forKey: .value)
    try container.encode(self.shippingValue, forKey: .shippingValue)
    try container.encodeIfPresent(self.shippingAddress, forKey: .shippingAddress)
    try container.encodeIfPresent(self.billingAddress, forKey: .billingAddress)
    try container.encodeIfPresent(self.user, forKey: .user)
    try container.encode(self.merchants, forKey: .merchants)
    try container.encode(self.items, forKey: .items)
    try container.encodeIfPresent(self.gatewayInfo, forKey: .gatewayInfo)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Structured address format for billing and shipping addresses.
  public struct Address: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The recipient name, potentially including information such as
    /// "care of".
    public var recipient: Swift.String = Swift.String()

    /// Optional. The first lines of the address. The first line generally
    /// contains the street name and number, and further lines may include
    /// information such as an apartment number.
    public var address: [Swift.String] = []

    /// Optional. The town/city of the address.
    public var locality: Swift.String = Swift.String()

    /// Optional. The state, province, or otherwise administrative area of the
    /// address.
    public var administrativeArea: Swift.String = Swift.String()

    /// Optional. The CLDR country/region of the address.
    public var regionCode: Swift.String = Swift.String()

    /// Optional. The postal or ZIP code of the address.
    public var postalCode: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Address`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Address().with { $0.recipient = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let recipient = CodingKeys(stringValue: "recipient")
      static let address = CodingKeys(stringValue: "address")
      static let locality = CodingKeys(stringValue: "locality")
      static let administrativeArea = CodingKeys(stringValue: "administrativeArea")
      static let regionCode = CodingKeys(stringValue: "regionCode")
      static let postalCode = CodingKeys(stringValue: "postalCode")

      static let _knownKeys: Set<Swift.String> = [
        "recipient",
        "address",
        "locality",
        "administrativeArea",
        "regionCode",
        "postalCode",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .recipient) {
        self.recipient = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .address) {
        self.address = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locality) {
        self.locality = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .administrativeArea) {
        self.administrativeArea = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .regionCode) {
        self.regionCode = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .postalCode) {
        self.postalCode = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.recipient, forKey: .recipient)
      try container.encode(self.address, forKey: .address)
      try container.encode(self.locality, forKey: .locality)
      try container.encode(self.administrativeArea, forKey: .administrativeArea)
      try container.encode(self.regionCode, forKey: .regionCode)
      try container.encode(self.postalCode, forKey: .postalCode)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.TransactionData.Address"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Details about a user's account involved in the transaction.
  public struct User: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Unique account identifier for this user. If using Account
    /// defense, this should match the hashed_account_id field. Otherwise, a
    /// unique and persistent identifier for this account.
    public var accountId: Swift.String = Swift.String()

    /// Optional. The epoch milliseconds of the user's account creation.
    public var creationMs: Swift.Int64 = Swift.Int64()

    /// Optional. The email address of the user.
    public var email: Swift.String = Swift.String()

    /// Optional. Whether the email has been verified to be accessible by the
    /// user (OTP or similar).
    public var emailVerified: Swift.Bool = Swift.Bool()

    /// Optional. The phone number of the user, with country code.
    public var phoneNumber: Swift.String = Swift.String()

    /// Optional. Whether the phone number has been verified to be accessible by
    /// the user (OTP or similar).
    public var phoneVerified: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `User`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = User().with { $0.accountId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let accountId = CodingKeys(stringValue: "accountId")
      static let creationMs = CodingKeys(stringValue: "creationMs")
      static let email = CodingKeys(stringValue: "email")
      static let emailVerified = CodingKeys(stringValue: "emailVerified")
      static let phoneNumber = CodingKeys(stringValue: "phoneNumber")
      static let phoneVerified = CodingKeys(stringValue: "phoneVerified")

      static let _knownKeys: Set<Swift.String> = [
        "accountId",
        "creationMs",
        "email",
        "emailVerified",
        "phoneNumber",
        "phoneVerified",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .accountId) {
        self.accountId = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .creationMs) {
        self.creationMs = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .email) {
        self.email = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .emailVerified) {
        self.emailVerified = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .phoneNumber) {
        self.phoneNumber = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .phoneVerified) {
        self.phoneVerified = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.accountId, forKey: .accountId)
      try container.encode(self.creationMs, forKey: .creationMs)
      try container.encode(self.email, forKey: .email)
      try container.encode(self.emailVerified, forKey: .emailVerified)
      try container.encode(self.phoneNumber, forKey: .phoneNumber)
      try container.encode(self.phoneVerified, forKey: .phoneVerified)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.TransactionData.User"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Line items being purchased in this transaction.
  public struct Item: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The full name of the item.
    public var name: Swift.String = Swift.String()

    /// Optional. The value per item that the user is paying, in the transaction
    /// currency, after discounts.
    public var value: Swift.Double = Swift.Double()

    /// Optional. The quantity of this item that is being purchased.
    public var quantity: Swift.Int64 = Swift.Int64()

    /// Optional. When a merchant is specified, its corresponding account_id.
    /// Necessary to populate marketplace-style transactions.
    public var merchantAccountId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Item`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Item().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let value = CodingKeys(stringValue: "value")
      static let quantity = CodingKeys(stringValue: "quantity")
      static let merchantAccountId = CodingKeys(stringValue: "merchantAccountId")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "value",
        "quantity",
        "merchantAccountId",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .value) {
        self.value = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .quantity) {
        self.quantity = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .merchantAccountId) {
        self.merchantAccountId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.value, forKey: .value)
      try container.encode(self.quantity, forKey: .quantity)
      try container.encode(self.merchantAccountId, forKey: .merchantAccountId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.TransactionData.Item"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Details about the transaction from the gateway.
  public struct GatewayInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Name of the gateway service (for example, stripe, square,
    /// paypal).
    public var name: Swift.String = Swift.String()

    /// Optional. Gateway response code describing the state of the transaction.
    public var gatewayResponseCode: Swift.String = Swift.String()

    /// Optional. AVS response code from the gateway
    /// (available only when reCAPTCHA Enterprise is called after authorization).
    public var avsResponseCode: Swift.String = Swift.String()

    /// Optional. CVV response code from the gateway
    /// (available only when reCAPTCHA Enterprise is called after authorization).
    public var cvvResponseCode: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GatewayInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GatewayInfo().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let gatewayResponseCode = CodingKeys(stringValue: "gatewayResponseCode")
      static let avsResponseCode = CodingKeys(stringValue: "avsResponseCode")
      static let cvvResponseCode = CodingKeys(stringValue: "cvvResponseCode")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "gatewayResponseCode",
        "avsResponseCode",
        "cvvResponseCode",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gatewayResponseCode)
      {
        self.gatewayResponseCode = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .avsResponseCode) {
        self.avsResponseCode = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cvvResponseCode) {
        self.cvvResponseCode = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.gatewayResponseCode, forKey: .gatewayResponseCode)
      try container.encode(self.avsResponseCode, forKey: .avsResponseCode)
      try container.encode(self.cvvResponseCode, forKey: .cvvResponseCode)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.TransactionData.GatewayInfo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.TransactionData"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
