// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Transaction data associated with a payment protected by reCAPTCHA Enterprise.
public struct TransactionData: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Unique identifier for the transaction. This custom identifier can be used
  /// to reference this transaction in the future, for example, labeling a refund
  /// or chargeback event. Two attempts at the same transaction should use the
  /// same transaction id.
  public var transactionId: Swift.String? = nil

  /// Optional. The payment method for the transaction. The allowed values are:
  ///
  /// * credit-card
  /// * debit-card
  /// * gift-card
  /// * processor-{name} (If a third-party is used, for example,
  /// processor-paypal)
  /// * custom-{name} (If an alternative method is used, for example,
  /// custom-crypto)
  public var paymentMethod: Swift.String = Swift.String()

  /// Optional. The Bank Identification Number - generally the first 6 or 8
  /// digits of the card.
  public var cardBin: Swift.String = Swift.String()

  /// Optional. The last four digits of the card.
  public var cardLastFour: Swift.String = Swift.String()

  /// Optional. The currency code in ISO-4217 format.
  public var currencyCode: Swift.String = Swift.String()

  /// Optional. The decimal value of the transaction in the specified currency.
  public var value: Swift.Double = Swift.Double()

  /// Optional. The value of shipping in the specified currency. 0 for free or no
  /// shipping.
  public var shippingValue: Swift.Double = Swift.Double()

  /// Optional. Destination address if this transaction involves shipping a
  /// physical item.
  public var shippingAddress: TransactionData.Address? = nil

  /// Optional. Address associated with the payment method when applicable.
  public var billingAddress: TransactionData.Address? = nil

  /// Optional. Information about the user paying/initiating the transaction.
  public var user: TransactionData.User? = nil

  /// Optional. Information about the user or users fulfilling the transaction.
  public var merchants: [TransactionData.User] = []

  /// Optional. Items purchased in this transaction.
  public var items: [TransactionData.Item] = []

  /// Optional. Information about the payment gateway's response to the
  /// transaction.
  public var gatewayInfo: TransactionData.GatewayInfo? = nil

  /// Initialize a new instance of `TransactionData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransactionData().with { $0.transactionId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Structured address format for billing and shipping addresses.
  public struct Address: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The recipient name, potentially including information such as
    /// "care of".
    public var recipient: Swift.String = Swift.String()

    /// Optional. The first lines of the address. The first line generally
    /// contains the street name and number, and further lines may include
    /// information such as an apartment number.
    public var address: [Swift.String] = []

    /// Optional. The town/city of the address.
    public var locality: Swift.String = Swift.String()

    /// Optional. The state, province, or otherwise administrative area of the
    /// address.
    public var administrativeArea: Swift.String = Swift.String()

    /// Optional. The CLDR country/region of the address.
    public var regionCode: Swift.String = Swift.String()

    /// Optional. The postal or ZIP code of the address.
    public var postalCode: Swift.String = Swift.String()

    /// Initialize a new instance of `Address`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Address().with { $0.recipient = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.TransactionData.Address"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Details about a user's account involved in the transaction.
  public struct User: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Unique account identifier for this user. If using Account
    /// defense, this should match the hashed_account_id field. Otherwise, a
    /// unique and persistent identifier for this account.
    public var accountId: Swift.String = Swift.String()

    /// Optional. The epoch milliseconds of the user's account creation.
    public var creationMs: Swift.Int64 = Swift.Int64()

    /// Optional. The email address of the user.
    public var email: Swift.String = Swift.String()

    /// Optional. Whether the email has been verified to be accessible by the
    /// user (OTP or similar).
    public var emailVerified: Swift.Bool = Swift.Bool()

    /// Optional. The phone number of the user, with country code.
    public var phoneNumber: Swift.String = Swift.String()

    /// Optional. Whether the phone number has been verified to be accessible by
    /// the user (OTP or similar).
    public var phoneVerified: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `User`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = User().with { $0.accountId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.TransactionData.User"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Line items being purchased in this transaction.
  public struct Item: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The full name of the item.
    public var name: Swift.String = Swift.String()

    /// Optional. The value per item that the user is paying, in the transaction
    /// currency, after discounts.
    public var value: Swift.Double = Swift.Double()

    /// Optional. The quantity of this item that is being purchased.
    public var quantity: Swift.Int64 = Swift.Int64()

    /// Optional. When a merchant is specified, its corresponding account_id.
    /// Necessary to populate marketplace-style transactions.
    public var merchantAccountId: Swift.String = Swift.String()

    /// Initialize a new instance of `Item`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Item().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.TransactionData.Item"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Details about the transaction from the gateway.
  public struct GatewayInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Name of the gateway service (for example, stripe, square,
    /// paypal).
    public var name: Swift.String = Swift.String()

    /// Optional. Gateway response code describing the state of the transaction.
    public var gatewayResponseCode: Swift.String = Swift.String()

    /// Optional. AVS response code from the gateway
    /// (available only when reCAPTCHA Enterprise is called after authorization).
    public var avsResponseCode: Swift.String = Swift.String()

    /// Optional. CVV response code from the gateway
    /// (available only when reCAPTCHA Enterprise is called after authorization).
    public var cvvResponseCode: Swift.String = Swift.String()

    /// Initialize a new instance of `GatewayInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GatewayInfo().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.TransactionData.GatewayInfo"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.TransactionData"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
