// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An identifier associated with a user.
public struct UserId: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var idOneof: OneOf_IdOneof? = nil

  /// Initialize a new instance of `UserId`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UserId().with { $0.email = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case email = "email"
    case phoneNumber = "phoneNumber"
    case username = "username"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var idOneof: OneOf_IdOneof? = nil
    let idOneofCheckAndSet = {
      if idOneof != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'idOneof'"))
      }
      idOneof = $0
    }
    if let email = try container.decodeIfPresent(Swift.String.self, forKey: .email) {
      try idOneofCheckAndSet(.email(email))
    }
    if let phoneNumber = try container.decodeIfPresent(Swift.String.self, forKey: .phoneNumber) {
      try idOneofCheckAndSet(.phoneNumber(phoneNumber))
    }
    if let username = try container.decodeIfPresent(Swift.String.self, forKey: .username) {
      try idOneofCheckAndSet(.username(username))
    }
    self.idOneof = idOneof
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.idOneof {
      switch choice {
      case .email(let value):
        try container.encode(value, forKey: .email)
      case .phoneNumber(let value):
        try container.encode(value, forKey: .phoneNumber)
      case .username(let value):
        try container.encode(value, forKey: .username)
      }
    }
  }

  public enum OneOf_IdOneof: Codable, Equatable, Sendable {
    /// Optional. An email address.
    case email(Swift.String)
    /// Optional. A phone number. Should use the E.164 format.
    case phoneNumber(Swift.String)
    /// Optional. A unique username, if different from all the other identifiers
    /// and `account_id` that are provided. Can be a unique login handle or
    /// display name for a user.
    case username(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.UserId"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
