// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// User information associated with a request protected by reCAPTCHA Enterprise.
public struct UserInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Creation time for this account associated with this user. Leave
  /// blank for non logged-in actions, guest checkout, or when there is no
  /// account associated with the current user.
  public var createAccountTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. For logged-in requests or login/registration requests, the unique
  /// account identifier associated with this user. You can use the username if
  /// it is stable (meaning it is the same for every request associated with the
  /// same user), or any stable user ID of your choice. Leave blank for non
  /// logged-in actions or guest checkout.
  public var accountId: Swift.String = Swift.String()

  /// Optional. Identifiers associated with this user or request.
  public var userIds: [UserId] = []

  /// Initialize a new instance of `UserInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UserInfo().with { $0.createAccountTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.UserInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
