// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Settings specific to keys that can be used for WAF (Web Application
/// Firewall).
public struct WafSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The Web Application Firewall (WAF) service that uses this key.
  public var wafService: WafSettings.WafService = WafSettings.WafService()

  /// Required. The Web Application Firewall (WAF) feature for which this key is
  /// enabled.
  public var wafFeature: WafSettings.WafFeature = WafSettings.WafFeature()

  /// Initialize a new instance of `WafSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WafSettings().with { $0.wafService = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Supported WAF features. For more information, see
  /// https://cloud.google.com/recaptcha/docs/usecase#comparison_of_features.
  /// Ensure that applications can handle values not explicitly listed.
  public enum WafFeature: Codable, Equatable, Sendable {
    /// Undefined feature.
    case unspecified
    /// Redirects suspicious traffic to reCAPTCHA.
    case challengePage
    /// Use reCAPTCHA session-tokens to protect the whole user session on the
    /// site's domain.
    case sessionToken
    /// Use reCAPTCHA action-tokens to protect user actions.
    case actionToken
    /// Deprecated: Use `express_settings` instead.
    @available(*, deprecated)
    case express
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .challengePage: return 1
      case .sessionToken: return 2
      case .actionToken: return 3
      case .express: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "WAF_FEATURE_UNSPECIFIED"
      case .challengePage: return "CHALLENGE_PAGE"
      case .sessionToken: return "SESSION_TOKEN"
      case .actionToken: return "ACTION_TOKEN"
      case .express: return "EXPRESS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:WafFeature/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "WAF_FEATURE_UNSPECIFIED": self = .unspecified
      case "CHALLENGE_PAGE": self = .challengePage
      case "SESSION_TOKEN": self = .sessionToken
      case "ACTION_TOKEN": self = .actionToken
      case "EXPRESS": self = .express
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:WafFeature/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .challengePage
      case 2: self = .sessionToken
      case 3: self = .actionToken
      case 5: self = .express
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .challengePage: return try container.encode(1)
      case .sessionToken: return try container.encode(2)
      case .actionToken: return try container.encode(3)
      case .express: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Web Application Firewalls that reCAPTCHA supports.
  /// Ensure that applications can handle values not explicitly listed.
  public enum WafService: Codable, Equatable, Sendable {
    /// Undefined WAF
    case unspecified
    /// Cloud Armor
    case ca
    /// Fastly
    case fastly
    /// Cloudflare
    case cloudflare
    /// Akamai
    case akamai
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ca: return 1
      case .fastly: return 3
      case .cloudflare: return 4
      case .akamai: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "WAF_SERVICE_UNSPECIFIED"
      case .ca: return "CA"
      case .fastly: return "FASTLY"
      case .cloudflare: return "CLOUDFLARE"
      case .akamai: return "AKAMAI"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:WafService/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "WAF_SERVICE_UNSPECIFIED": self = .unspecified
      case "CA": self = .ca
      case "FASTLY": self = .fastly
      case "CLOUDFLARE": self = .cloudflare
      case "AKAMAI": self = .akamai
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:WafService/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ca
      case 3: self = .fastly
      case 4: self = .cloudflare
      case 5: self = .akamai
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ca: return try container.encode(1)
      case .fastly: return try container.encode(3)
      case .cloudflare: return try container.encode(4)
      case .akamai: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recaptchaenterprise.v1.WafSettings"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
